### ISSUE TITLE
__builtin_shufflevector

### ISSUE THREAD

**Issue by PegX** [ftramer/slalom#12]
Hello, i wanna ask how to solve "__builtin_shufflevector" problem during the compiling. I encountered this issue during the make.
Is it possible to cause by different compilers?

**Comment by ftramer** [comment]
Difficult to say without more information on the error. From a quick Google search it seems that this is a Clang specific extension?
All the development was done with GCC so it's definitely possible that there would be weird issues when moving to Clang.

**Comment by PegX** [comment]
When i do the "make" step in slalom/App directory. I got many errors. These errors are very similar with the following:

.local/lib/python2.7/site-packages/tensorflow/include/third_party/eigen3/unsupported/Eigen/CXX11/src/FixedPoint/MatMatProductAVX2.h:1719:17: error: there are no arguments to '__builtin_shufflevector' that depend on a template parameter, so a declaration of '__builtin_shufflevector' must be available [-fpermissive]
         R_EH3 = _mm256_shuffle_epi32(R_AH0_, 0xFF);

I googled and got the information about '__builtin_shufflevector' . That is the plugin for clang compiler. The problem here is how can I solve this issue. 

Thanks very much for your suggest.

**Comment by ftramer** [comment]
Are you trying to compile this on OSX? If so, you're probably using Apple's clang compiler rather than gcc. This might be fixable by installing gcc (e.g., with homebrew) but I haven't tried installing Slalom on any other system than Ubuntu so I can't guarantee this will work (e.g., I'm not sure if the SGX drivers and libraries can be installed on OSX).
