### ISSUE TITLE
Parallelization is working?

### ISSUE THREAD

**Issue by anddev68** [ftramer/slalom#31]
Hello. Thank you for grateful work, slalom.
I have some questions.

1. However, I guess that following code do not work as parallel. Because `batch_size` is always 1, isn't it?
1. Even If we fix the problem as mentioned above, openMP works on SGX applications?

eval.py

```
for i in range(args.batch_size):
  pred = sgxutils.predict(images[i:i + 1], num_classes=num_classes)
```

sgxdnn.py 

```
def predict(self, x, num_classes=1000, eid_idx=0):
  predict_method(inp_ptr, res_ptr, x.shape[0])
```

enclave_bridge.cpp

```
    void predict_float(unsigned long int eid, float* input, float* output, int batch_size) {
		#pragma omp parallel for num_threads(3)
		for (int i=0; i<batch_size; i++) {
```

**Comment by ftramer** [comment]
The current code doesn't use any parallelism inside the enclave.
Doing this is non-trivial as threads are managed by the OS. We did try some experiments where multiple threads enter the same enclave to form a pool, but we did not see much of a performance benefit (presumably because the inter-thread synchronization is more expensive inside the enclave).

Note that the code in `enclave_bridge.cpp` is run outside of the enclave, and is responsible for calling into the enclave. 
The openMP loop in there was actually a relic from an unsuccessful experiment I had run. I've now removed it.
You're right that this had no effect anyways if the batch size was set to 1.
