### ISSUE TITLE
Question about fixed-point representation

### ISSUE THREAD

**Issue by hyunsooda** [ftramer/slalom#43]
Hi, @ftramer
Thanks for the interesting work :) I have two questions, please.

1.  The First question is about the fixed-point representation you used. ```xhat = FP(x; k) := round(2^k * x).```
Can you explain how this expression is derived? also, what we have wrong if we adopt the simplest method like ```round(x)```?

2. > For efficiency reasons, we perform integer arithmetic using floats

I couldn't understand what it means exactly. As far as I know, the performance between integer ops and float ops are depended on processor by processor or application by application. Can you unpack it for clarity?

**Comment by ftramer** [comment]
1. Suppose `x` takes floating-point values between `0` and `1`. Then simply applying `round(x)` will destroy all the signal as everything is mapped to `0`. By first multiplying by `2^k`, we ensure that our floating points get distributed into a larger interval `[0, 2^k]` that contains `2^k + 1` different integers. We thus get a much more accurate fixed-point representation.

2. Yes, you're right that the performance of int or float ops depends on the hardware. It turns out that for modern Intel CPUs and GPUs, float ops are typically much faster than int ops. E.g., on Intel architectures, this is due to the availability of better SIMD instructions for floats, which allow for computing many float ops in parallel. Such instructions also exist for ints, but they're typically slower.

**Comment by hyunsooda** [comment]
Thanks for the clear answer!
Let me close this thread.
